const express =require ('express')
const router=express.Router()
const userController=require('../controllers/users')
const verifyToken = require('../middleware/verifyToken')

router.get('/all',userController.getUser)
router.get('/create',userController.getCreateUser )
router.get('/update/:id', userController.getUpdateUser)
router.get('/delete/:id', userController.getDeleteUser)
router.get('/createAdmin', userController.getcreateAdmin)
router.get('/allA',userController.getAdmin)
router.get('/admin',userController.getAdmin)
router.get('/updatea/:id', userController.getUpdateAdmin)
router.get('/deletea/:id', userController.getDeleteAdmin)
router.get('/store',userController.getStore)

router.post('/create',userController.createUser)
router.post('/update/:id',userController.updateUser)
router.post('/delete/:id',userController.deleteUser)
router.post('/register', userController.register)
router.post('/updatea/:id',userController.updateAdmin)
router.post('/deletea/:id',userController.deleteAdmin)


//Rutas de Rada
router.get('/menu',userController.getIndex)
router.get('/count',userController.getCount)
router.get('/tablero',userController.getTablero)
router.get('/contact',userController.getContact)
router.get('/message',userController.getMessage)
router.get('/tarea',userController.getTarea)
router.get('/form',userController.getForm)
router.get('/tabla',userController.getTabla )
router.get('/graph',userController.getGraph)
router.get('/perfil/:id',userController.getPerfil)
router.get('/artistas',userController.getArtistas)
router.get('/radacontact',userController.getSendmsg)
router.get('/deletemsg/:id',userController.deleteMsg)
router.get('/crearTarea',userController.getCreateTask)
router.get('/eliminarTarea/:id',userController.deleteTask)
router.get('/turn/:id',userController.cambiarBoton)
router.get('/updateTask/:id',userController.getUpdateTask)

router.post('/login', userController.login)
router.post('/solicitud',userController.sendSupport)
router.post('/createartist',userController.createArtist)
router.post('/add',userController.subirImagen)
router.post('/envioMsg',userController.msgEnvio)
router.post('/subirTarea',userController.crearTask)
router.post('/updateTask/:id',userController.updateTask)
module.exports=router